language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install opencv-python --user
# command to run tests
script:
  - python extract_embeddings.py
  - python train_model.py
  - python recognize.py -i images/tom1.jpg
